// js/core/state.js

// 1. Global application state properties
export const state = {
    currentLang: "RUS",
    percent: 0,
    gTarget: 8000,
    cSav: 0
};

// 2. Localization translations dictionary
export const TRANSLATIONS = {
    RUS: {
    t_work_data: "Данные о работе", l_date: "📅 Дата", l_status: "📌 Статус",
    opt_work: "💼 Работа", opt_l4: "💊 Больничный (L4)", opt_urlop: "🌴 Отпуск",
    l_end_date: "🏁 По (включительно)", l_object: "📍 Объект / Город", 
    l_abroad: "🌍 Заграница (EUR)", l_diet: "🥪 Командировка (Диета)",
    t_logistics: "Логистика и Часы", l_car: "🚛 Авто", l_route: "🛣 Маршрут",
    l_hours: "⏱ На объекте (ч)", l_drive: "🚗 За рулем (ч)", btn_send_shift: "Отправить отчет",
    t_progress: "🎯 Моя копилка", t_audit: "📊 Аудит выплат",
    l_month_audit: "📅 Месяц", l_card: "💰 Пришло на карту", btn_audit: "⚖️ Аудит выплат",
    t_history: "📜 История", l_month_history: "Выбери месяц", btn_history: "📂 Просмотр смен",
    btn_history_edit: "✏️ Редактирование смен",
    t_export: "📥 Экспорт Excel", l_month_export: "Выбери месяц", btn_export: "Прислать Excel в чат",
    btn_export_boss: "👨‍💼 Отчет для шефа",
    t_lang: "Язык интерфейса", l_lang_select: "🌐 Язык", t_goal: "🎯 Моя финансовая цель", l_goal_name: "Название",
    l_goal_sum: "Сумма (zł)", t_profile: "Финансовый профиль (Ставки)", btn_save_settings: "Сохранить настройки",
    alert_hours: "⚠️ Укажи часы работы ИЛИ за рулем!", alert_audit: "⚠️ Выбери месяц и введи сумму!", alert_history: "⚠️ Выбери месяц для просмотра истории!",
    mot_start: "Начало положено! 🚀 Отложи первую сумму.", mot_good: "Отличный старт! Двигаемся дальше. 💼", mot_fast: "Хороший темп! Копилка пополняется. 🔥", mot_close: "Уже близко! Поднажми! 💪", mot_done: "ЦЕЛЬ ДОСТИГНУТА! 🎉 Ты супер-профи!",
    default_goal: "Моя цель", objectInput: "Любой текст", routeInput: "Откуда - Куда", cardAmount: "Сумма в zł", goalNameInput: "Дом у моря", goalMotivation: "Загружаем данные...",
    t_analytics: "📈 Топ объектов", l_month_analytics: "Выбери месяц", btn_analytics: "Показать Топ объектов",
    l_goal_date: "К какому сроку?", l_base_rate: "💳 Офиц. ставка (zł/h)", l_env: "⚖️ Целевая ставка (zł/h)", l_rate_eur: "💶 Ставка (EUR/h)", l_drive_zl: "🚗 Руль (zł/h)", l_drive_eur: "🚙 Руль (EUR/h)",
    t_garage: "Мой Гараж", 
    t_garage_desc: "Кася может автоматически распознать марку и номер машины по фотографии!",
    t_nav: "Навигация", 
    t_nav_desc: "Введи точки маршрута, и Кася проложит путь прямо в твоем навигаторе!",
    t_envelope_desc: "Кася сверит твои часы с переводами на карту и рассчитает Nierozliczone saldo!",
    t_history_desc: "Кася поднимет архивы за выбранный месяц, чтобы ты мог просмотреть или изменить свои записи.",
    t_export_desc: "Кася аккуратно соберет все твои смены за месяц и пришлет готовый файл Excel прямо в Телеграм!",
    t_analytics_desc: "Кася проанализирует твои смены и покажет, какие объекты принесли тебе больше всего часов в этом месяце.",
    l_history_edit_date: "Выбрать день для удаления/изменения:", btn_export_logistics: "🚚 Отчет для логиста", btn_vacation_stats: "🌴 Статус отпуска",
    t_feedback_title: "💬 Обратная связь", feedbackTextInput: "Напишите ваш отзыв, предложение или баг-репорт...", btn_send_feedback: "Отправить отзыв", alert_feedback_empty: "⚠️ Пожалуйста, введите текст отзыва перед отправкой!",
    help_title: "Справка",
    help_work_data: "Заполните дату смены, ее тип (Работа, L4, Отпуск) и объект. Отметьте 'Заграница', если работали вне Польши, или 'Командировка', если полагается диета.",
    help_logistics: "Укажите часы работы и вождения, а также маршрут и автомобиль. Если вы укажете маршрут без часов вождения, бот рассчитает их автоматически.",
    help_garage: "Здесь вы можете выбрать текущий автомобиль или сфотографировать его номер по кнопке сканера, чтобы Кася распознала его с помощью ИИ.",
    help_nav: "Введите точки отправления и назначения, чтобы проложить оптимальный маршрут в Google Maps. Кася также скопирует этот маршрут в отчет!",
    help_audit: "Запустите сравнение ваших отработанных часов со ставками и полученными переводами. Кася рассчитает ваше Nierozliczone saldo за выбранный месяц.",
    help_history: "Просматривайте историю ваших смен за любой месяц и удаляйте ошибочные записи при необходимости.",
    help_export: "Выгружайте подробный Excel-отчет о вашей работе прямо в чат Telegram. Отчет для шефа защитит вашу конфиденциальность и скроет финансовые данные.",
    help_analytics: "Анализируйте распределение вашего рабочего времени по различным объектам и городам за выбранный месяц.",
    help_savings: "Следите за движением к вашей финансовой цели в копилке. Процент выполнения цели рассчитывается автоматически по мере сохранения смен.",
    help_lang: "Выберите язык интерфейса WebApp и сообщений от бота.",
    help_goal: "Укажите вашу финансовую цель, целевую сумму и срок выполнения. Кася рассчитыет необходимый темп накоплений.",
    help_profile: "Задайте ставки для различных типов работ: официальную, целевую (Stawka docelowa), заграничную, за рулем и т.д.",
    l_how_it_works: "Как это работает?",
    garageCarInput: "Выбери или введи авто",
    l_garage_car: "🚗 Текущий автомобиль:",
    btn_scan_car: "📸 Включить сканер",
    l_route_from: "🅰️ Откуда:",
    l_route_to: "🅱️ Куда:",
    routeFrom: "Например: Zielona Góra",
    routeTo: "Город или Объект",
    btn_google_maps: "🗺️ Поехали!",
    btn_save_shift: "Сохранить изменения",
    l_polaroid_caption: "Моя Кася 🖤",
    btn_scan_take_photo: "🔴 Сделать снимок!",
    camera_no_access: "⚠️ Ошибка: нет доступа к камере. Разреши Telegram использовать камеру в настройках телефона!",
    kasia_thinking: "Кася думает... 🧠",
    scan_recognized: "✅ Распознано: ",
    scan_server_err: "❌ Ошибка сервера (пока не подключен ИИ).",
    scan_backend_offline: "⚠️ Бэкенд с ИИ пока не подключен, но фото успешно сделано!",
    alert_route_to_required: "⚠️ Кася просит указать хотя бы точку назначения (Куда)!"
  },
    UKR: {
    t_work_data: "Дані про роботу", l_date: "📅 Дата", l_status: "📌 Status",
    opt_work: "💼 Робота", opt_l4: "💊 Лікарняний (L4)", opt_urlop: "🌴 Відпустка",
    l_end_date: "🏁 По (включно)", l_object: "📍 Об'єкт / Місто", 
    l_abroad: "🌍 Закордон (EUR)", l_diet: "🥪 Відрядження (Дієта)",
    t_logistics: "Логістика та Години", l_car: "🚛 Авто", l_route: "🛣 Маршрут",
    l_hours: "⏱ На об'єкті (год)", l_drive: "🚗 За кермом (год)", btn_send_shift: "Відправити звіт",
    t_progress: "🎯 Moя скарбничка", t_audit: "📊 Аудит виплат",
    l_month_audit: "📅 Місяць", l_card: "💰 Прийшло на карту", btn_audit: "⚖️ Аудит виплат",
    t_history: "📜 Історія", l_month_history: "Обери місяць", btn_history: "📂 Перегляд змін",
    btn_history_edit: "✏️ Редагування змін",
    t_export: "📥 Експорт Excel", l_month_export: "Обери місяць", btn_export: "Надіслати Excel у чат",
    btn_export_boss: "👨‍💼 Звіт для шефа",
    t_lang: "Мова інтерфейсу", l_lang_select: "🌐 Мова", t_goal: "🎯 Моя фінансова ціль", l_goal_name: "Назва",
    l_goal_sum: "Сума (zł)", t_profile: "Фінансовий профіль (Ставки)", btn_save_settings: "Зберегти зміни",
    alert_hours: "⚠️ Вкажи години роботи АБО за кермом!", alert_audit: "⚠️ Обери місяць та введи суму!", alert_history: "⚠️ Обери місяць для перегляду історії!",
    mot_start: "Початок покладено! 🚀", mot_good: "Гарний start! 💼", mot_fast: "Хороший темп! 🔥", mot_close: "Вже близько! 💪", mot_done: "ЦІЛЬ ДОСЯГНУТА! 🎉",
    default_goal: "Моя ціль", objectInput: "Будь-який текст", routeInput: "Звідки - Куди", cardAmount: "Сума в zł", goalNameInput: "Будинок біля моря", goalMotivation: "Завантажуємо дані...",
    t_analytics: "📈 Топ об'єктів", l_month_analytics: "Обери місяць", btn_analytics: "Показати Топ об'єктів",
    l_goal_date: "До якого терміну?", l_base_rate: "💳 Офіц. ставка (zł/h)", l_env: "⚖️ Цільова ставка (zł/h)", l_rate_eur: "💶 Ставка (EUR/h)", l_drive_zl: "🚗 Кермо (zł/h)", l_drive_eur: "🚙 Кермо (EUR/h)",
    t_garage: "Мій Гараж", 
    t_garage_desc: "Кася може автоматично розпізнати марку та номер машини за фотографією!",
    t_nav: "Навігація", 
    t_nav_desc: "Введи точки маршруту, і Кася проложит шлях прямо в твоєму навігаторі!",
    t_envelope_desc: "Кася звірить твої години з переказами на карту і розрахує Nierozliczone saldo!",
    t_history_desc: "Кася підніме архіви за обраний місяць, щоб ти міг переглянути або змінити свої записи.",
    t_export_desc: "Кася акуратно збере всі твої зміни за місяць і надішле готовий файл Excel прямо в Телеграм!",
    t_analytics_desc: "Кася проаналізує твої зміни і покаже, які об'єкти принесли тобі найбільше годин цього місяця.",
    l_history_edit_date: "Обрати день для видалення/зміни:", btn_export_logistics: "🚚 Звіт для логіста", btn_vacation_stats: "🌴 Статус відпустки",
    t_feedback_title: "💬 Зворотній зв'язок", feedbackTextInput: "Напишіть ваш відгук, пропозицію або баг-репорт...", btn_send_feedback: "Надіслати відгук", alert_feedback_empty: "⚠️ Будь ласка, введіть текст відгуку перед відправкою!",
    help_title: "Довідка",
    help_work_data: "Заповніть дату зміни, її тип (Робота, L4, Відпустка) та об'єкт. Позначте 'Закордон', якщо працювали поза межами Польщі, або 'Відрядження', якщо передбачена дієта.",
    help_logistics: "Вкажіть години роботи та водіння, а також маршрут і автомобіль. Якщо ви вкажете маршрут без годин водіння, бот розрахує їх автоматично.",
    help_garage: "Тут ви можете обрати поточний автомобіль або сфотографувати його номер за кнопкою сканера, щоб Кася розпізнала його за допомогою ШІ.",
    help_nav: "Введіть точки відправлення та призначення, щоб прокласти оптимальний маршрут у Google Maps. Кася також скопіює цей маршрут у звіт!",
    help_audit: "Запустіть порівняння ваших відпрацьованих годин зі ставками та отриманими переказами. Кася розрахує ваше Nierozliczone saldo за обраний місяць.",
    help_history: "Переглядайте історію ваших змін за будь-який місяць та видаляйте помилкові записи за потреби.",
    help_export: "Завантажуйте детальний Excel-звіт про вашу роботу прямо в чат Telegram. Звіт для шефа захистить вашу конфіденційність та приховає фінансові дані.",
    help_analytics: "Аналізуйте розподіл вашого робочого часу за різними об'єктами та містами за обраний місяць.",
    help_savings: "Слідкуйте за рухом до Вашої фінансової мети у скарбничці. Відсоток виконання мети розраховується автоматично по мірі збереження змін.",
    help_lang: "Оберіть мову інтерфейсу WebApp та повідомлень від бота.",
    help_goal: "Вкажіть вашу фінансову мету, цільову суму та термін виконання. Кася розрахує необхідний темп накопичень.",
    help_profile: "Задайте ставки для різних типів робіт: офіційну, цільову (Stawka docelowa), закордонну, за кермом тощо.",
    l_how_it_works: "Як це працює?",
    garageCarInput: "Обери або введи авто",
    l_garage_car: "🚗 Поточний автомобіль:",
    btn_scan_car: "📸 Увімкнути сканер",
    l_route_from: "🅰️ Звідки:",
    l_route_to: "🅱️ Куди:",
    routeFrom: "Наприклад: Zielona Góra",
    routeTo: "Місто або Об'єкт",
    btn_google_maps: "🗺️ Поїхали!",
    btn_save_shift: "Зберегти зміни",
    l_polaroid_caption: "Моя Кася 🖤",
    btn_scan_take_photo: "🔴 Зробити знімок!",
    camera_no_access: "⚠️ Помилка: немає доступу до камери. Дозволь Telegram використовувати камеру в налаштуваннях телефону!",
    kasia_thinking: "Кася думає... 🧠",
    scan_recognized: "✅ Розпізнано: ",
    scan_server_err: "❌ Помилка сервера (поки що не підключено ШІ).",
    scan_backend_offline: "⚠️ Бекенд з ШІ поки що не підключено, але фото успішно зроблено!",
    alert_route_to_required: "⚠️ Кася просить вказати хоча б точку призначення (Куди)!"
  },
    PL: {
    t_work_data: "Dane o pracy", l_date: "📅 Data", l_status: "📌 Status",
    opt_work: "💼 Praca", opt_l4: "💊 Zwolnienie (L4)", opt_urlop: "🌴 Urlop",
    l_end_date: "🏁 Do (włącznie)", l_object: "📍 Obiekt / Miasto", 
    l_abroad: "🌍 Zagranica (EUR)", l_diet: "🥪 Delegacja (Dieta)",
    t_logistics: "Logistyka i Godziny", l_car: "🚛 Auto", l_route: "🛣 Trasa",
    l_hours: "⏱ Na obiekcie (h)", l_drive: "🚗 Za kierownicą (h)", btn_send_shift: "Wyślij raport",
    t_progress: "🎯 Moja skarbonka", t_audit: "📊 Audyt wyrównania",
    l_month_audit: "📅 Miesiąc", l_card: "💰 Wpłynęło na konto", btn_audit: "⚖️ Audyt wyrównania",
    t_history: "📜 Historia", l_month_history: "Wybierz miesiąc", btn_history: "📂 Podgląd zmian",
    btn_history_edit: "✏️ Edycja zmian",
    t_export: "📥 Eksport Excel", l_month_export: "Wybierz miesiąc", btn_export: "Wyślij Excel",
    btn_export_boss: "👨‍💼 Raport dla szefa",
    t_lang: "Język interfejsu", l_lang_select: "🌐 Język", t_goal: "🎯 Mój cel finansowy", l_goal_name: "Nazwa",
    l_goal_sum: "Kwota (zł)", t_profile: "Profil finansowy (Stawki)", btn_save_settings: "Zapisz ustawienia",
    alert_hours: "⚠️ Podaj godziny pracy LUB za kierownicą!", alert_audit: "⚠️ Wybierz miesiąc i wpisz kwotę!", alert_history: "⚠️ Wybierz miesiąc!",
    mot_start: "Początek zrobiony! 🚀", mot_good: "Świetny start! 💼", mot_fast: "Dobre tempo! 🔥", mot_close: "Już blisko! 💪", mot_done: "CEL OSIĄGNIĘTY! 🎉",
    default_goal: "Mój cel", objectInput: "Dowolny tekst", routeInput: "Skąd - Dokąd", cardAmount: "Kwota w zł", goalNameInput: "Dom nad morzem", goalMotivation: "Wczytywanie...",
    t_analytics: "📈 Top obiektów", l_month_analytics: "Wybierz miesiąc", btn_analytics: "Pokaż Top obiektów",
    l_goal_date: "Do kiedy?", l_base_rate: "💳 Ofic. stawka (zł/h)", l_env: "⚖️ Stawka docelowa (zł/h)", l_rate_eur: "💶 Stawka (EUR/h)", l_drive_zl: "🚗 Kółko (zł/h)", l_drive_eur: "🚙 Kółko (EUR/h)",
    t_garage: "Mój Garaż", 
    t_garage_desc: "Kasia może automatycznie rozpoznać markę i numer rejestracyjny samochodu na podstawie zdjęcia!",
    t_nav: "Nawigacja", 
    t_nav_desc: "Wpisz punkty trasy, a Kasia wyznaczy drogę prosto w Twojej nawigacji!",
    t_envelope_desc: "Kasia porówna Twoje godziny z przelewami na konto i wyliczy Twoje Nierozliczone saldo!",
    t_history_desc: "Kasia wyciągnie archiwa za wybrany miesiąc, abyś mógł przejrzeć lub edytować swoje wpisy.",
    t_export_desc: "Kasia starannie zbierze wszystkie Twoje zmiany za miesiąc i wyśle gotowy plik Excel prosto na Telegram!",
    t_analytics_desc: "Kasia przeanalizuje Twoje zmiany i pokaże, które obiekty przyniosły Ci najwięcej godzin w tym miesiącu.",
    l_history_edit_date: "Wybierz dzień do usunięcia/edycji:", btn_export_logistics: "🚚 Raport dla logisty", btn_vacation_stats: "🌴 Status urlopu",
    t_feedback_title: "💬 Informacje zwrotne", feedbackTextInput: "Wpisz swoją opinię, sugestię lub zgłoszenie błędu...", btn_send_feedback: "Wyślij opinię", alert_feedback_empty: "⚠️ Wpisz treść opinii przed wysłaniem!",
    help_title: "Pomoc",
    help_work_data: "Wpisz datę zmiany, status (Praca, L4, Urlop) i obiekt. Zaznacz 'Zagranica', jeśli pracowałeś poza Polską, lub 'Delegacja', jeśli przysługuje dieta.",
    help_logistics: "Podaj godziny pracy i jazdy oraz trasę i samochód. Jeśli wpisz trasę bez godzin jazdy, bot obliczy je automatycznie.",
    help_garage: "Tutaj możesz wybrać bieżący samochód lub zrobić zdjęcie tablicy rejestracyjnej, aby Kasia rozpoznała ją automatycznie za pomocą AI.",
    help_nav: "Wpisz punkty trasy, aby wyznaczyć optymalną drogę w Google Maps. Kasia również skopiuje tę trasę do Twojego raportu!",
    help_audit: "Uruchom porównanie przepracowanych godzin ze stawkami i przelewami na konto. Kasia wyliczy Twoje Nierozliczone saldo za dany miesiąc.",
    help_history: "Przeglądaj historię swoich wpisów za dowolny miesiąc i w razie potrzeby usuwaj błędne wpisy.",
    help_export: "Pobieraj szczegółowy raport Excel za wybrany miesiąc. Specjalny raport dla szefa ukryje wszelkie dane finansowe i stawki.",
    help_analytics: "Analizuj czas pracy w podziale na poszczególne obiekty i miasta w wybranym miesiącu.",
    help_savings: "Śledź postępy w realizacji swojego celu finansowego w skarbonce. Procent celu jest wyliczany automatycznie na podstawie wpisów.",
    help_lang: "Wybierz język interfejsu WebApp i wiadomości od bota.",
    help_goal: "Wpisz swój cel finansowy, kwotę i termin realizacji. Kasia wylicz wymagane tempo oszczędzania.",
    help_profile: "Zdefiniuj swoje stawki dla różnych rodzajów pracy: oficjalną, docelową (Stawka docelowa), zagraniczną, za kierownicą itd.",
    l_how_it_works: "Jak to działa?",
    garageCarInput: "Wybierz lub wpisz auto",
    l_garage_car: "🚗 Bieżący samochód:",
    btn_scan_car: "📸 Włącz skaner",
    l_route_from: "🅰️ Skąd:",
    l_route_to: "🅱️ Dokąd:",
    routeFrom: "Np. Zielona Góra",
    routeTo: "Miasto lub Obiekt",
    btn_google_maps: "🗺️ Ruszajmy!",
    btn_save_shift: "Zapisz zmiany",
    l_polaroid_caption: "Moja księgowa 🖤",
    btn_scan_take_photo: "🔴 Zrób zdjęcie!",
    camera_no_access: "⚠️ Błąd: brak dostępu do kamery. Zezwól aplikacji Telegram na używanie kamery w ustawieniach telefonu!",
    kasia_thinking: "Kasia myśli... 🧠",
    scan_recognized: "✅ Rozpoznano: ",
    scan_server_err: "❌ Błąd serwera (na razie brak połączenia z AI).",
    scan_backend_offline: "⚠️ Serwer AI nie jest jeszcze podłączony, ale zdjęcie zostało pomyślnie zrobione!",
    alert_route_to_required: "⚠️ Kasia prosi o wskazanie przynajmniej punktu docelowego (Dokąd)!"
    },
  ENG: {
    t_work_data: "Work Data", l_date: "📅 Date", l_status: "📌 Status",
    opt_work: "💼 Work", opt_l4: "💊 Sick Leave (L4)", opt_urlop: "🌴 Vacation",
    l_end_date: "🏁 To (inclusive)", l_object: "📍 Object / City", 
    l_abroad: "🌍 Abroad (EUR)", l_diet: "🥪 Travel Allowance",
    t_logistics: "Logistics and Hours", l_car: "🚛 Car", l_route: "🛣 Route",
    l_hours: "⏱ On Site (h)", l_drive: "🚗 Driving (h)", btn_send_shift: "Submit Report",
    t_progress: "🎯 My Piggy Bank", t_audit: "📊 Compensation Audit",
    l_month_audit: "📅 Month", l_card: "💰 Received on Card", btn_audit: "⚖️ Compensation Audit",
    t_history: "📜 History", l_month_history: "Select Month", btn_history: "📂 View Shifts",
    btn_history_edit: "✏️ Edit Shifts",
    t_export: "📥 Export Excel", l_month_export: "Select Month", btn_export: "Send Excel to Chat",
    btn_export_boss: "👨‍💼 Report for Manager",
    t_lang: "Interface Language", l_lang_select: "🌐 Language", t_goal: "🎯 My Financial Goal", l_goal_name: "Name",
    l_goal_sum: "Amount (zł)", t_profile: "Financial Profile (Rates)", btn_save_settings: "Save Settings",
    alert_hours: "⚠️ Specify work hours OR driving hours!", alert_audit: "⚠️ Select month and enter amount!", alert_history: "⚠️ Select month to view history!",
    mot_start: "A start has been made! 🚀 Put aside the first amount.", mot_good: "Great start! Moving forward. 💼", mot_fast: "Good pace! Piggy bank is filling up. 🔥", mot_close: "Almost there! Keep pushing! 💪", mot_done: "GOAL REACHED! 🎉 You are a super-pro!",
    default_goal: "My Goal", objectInput: "Any text", routeInput: "From - To", cardAmount: "Amount in zł", goalNameInput: "House by the sea", goalMotivation: "Loading...",
    t_analytics: "📈 Top Objects", l_month_analytics: "Select Month", btn_analytics: "Show Top Objects",
    l_goal_date: "By when?", l_base_rate: "💳 Official Rate (zł/h)", l_env: "⚖️ Target Rate (Stawka docelowa) (zł/h)", l_rate_eur: "💶 Rate (EUR/h)", l_drive_zl: "🚗 Driving (zł/h)", l_drive_eur: "🚙 Driving (EUR/h)",
    t_garage: "My Garage", 
    t_garage_desc: "Kasia can automatically recognize the car make and license plate from a photo!",
    t_nav: "Navigation", 
    t_nav_desc: "Enter route points, and Kasia will plan the path directly in your navigator!",
    t_envelope_desc: "Kasia will reconcile your hours with card transfers and calculate the Unresolved balance (Nierozliczone saldo)!",
    t_history_desc: "Kasia will retrieve archives for the selected month so you can view or modify your entries.",
    t_export_desc: "Kasia will carefully compile all your shifts for the month and send a ready Excel file directly to Telegram!",
    t_analytics_desc: "Kasia will analyze your shifts and show which objects brought you the most hours this month.",
    l_history_edit_date: "Select day to edit/delete:", btn_export_logistics: "🚚 Report for Logistics", btn_vacation_stats: "🌴 Vacation Status",
    t_feedback_title: "💬 Feedback", feedbackTextInput: "Write your feedback, suggestion, or bug report...", btn_send_feedback: "Send Feedback", alert_feedback_empty: "⚠️ Please enter feedback text before sending!",
    help_title: "Help",
    help_work_data: "Fill in the shift date, its status (Work, Sick Leave (L4), Vacation) and object. Check 'Abroad' if you worked outside of Poland, or 'Travel Allowance' if a diet allowance applies.",
    help_logistics: "Specify work and driving hours, as well as the route and vehicle. If you specify a route without driving hours, the bot will calculate them automatically.",
    help_garage: "Here you can select the current vehicle or take a photo of its license plate using the scanner button so Kasia can recognize it using AI.",
    help_nav: "Enter departure and destination points to calculate the optimal route in Google Maps. Kasia will also copy this route to the report!",
    help_audit: "Run a comparison of your hours worked with rates and received transfers. Kasia will calculate your Unresolved balance (Nierozliczone saldo) for the selected month.",
    help_history: "View the history of your shifts for any month and delete incorrect entries if necessary.",
    help_export: "Export a detailed Excel report of your work directly to Telegram chat. The Manager Report will protect your privacy and hide financial details.",
    help_analytics: "Analyze the distribution of your work time across different objects and cities for the selected month.",
    help_savings: "Track progress toward your financial goal in the piggy bank. The goal completion percentage is calculated automatically as shifts are saved.",
    help_lang: "Select the interface language for the WebApp and bot messages.",
    help_goal: "Specify your financial goal, target amount, and deadline. Kasia will calculate the required savings pace.",
    help_profile: "Set rates for different types of work: official rate, target rate (Stawka docelowa), abroad rate, driving rate, etc.",
    l_how_it_works: "How it works?",
    garageCarInput: "Select or enter vehicle",
    l_garage_car: "🚗 Current vehicle:",
    btn_scan_car: "📸 Enable Scanner",
    l_route_from: "🅰️ From:",
    l_route_to: "🅱️ To:",
    routeFrom: "Example: Zielona Góra",
    routeTo: "City or Object",
    btn_google_maps: "🗺️ Let's go!",
    btn_save_shift: "Save Changes",
    l_polaroid_caption: "My Kasia 🖤",
    btn_scan_take_photo: "🔴 Take Photo!",
    camera_no_access: "⚠️ Error: no camera access. Allow Telegram to use the camera in phone settings!",
    kasia_thinking: "Kasia is thinking... 🧠",
    scan_recognized: "✅ Recognized: ",
    scan_server_err: "❌ Server error (AI not connected yet).",
    scan_backend_offline: "⚠️ AI backend is not connected yet, but the photo was successfully taken!",
    alert_route_to_required: "⚠️ Kasia asks to specify at least the destination point (To)!"
  }
};