# texts.py

import random

TRANSLATIONS = {
    "RUS": {
        "saving": "⏳ Сохраняю...",
        "report_wait": "⏳ Формирую отчет за {month}...",
        "total_month": "Итого за месяц:",
        "freemium": "🤝 **Напарник, минутку внимания!**\n\nЭто твой **{count}-й** сгенерированный отчет. Я экономлю тебе кучу времени на сверках с офисом и расчетах налогов.\n\nЧтобы бот работал стабильно и развивался дальше, ты можешь поддержать проект символической суммой «на кофе ☕».",
        "audit_ok": "⚖️ **Аудит за {month}**\n\n💳 Пришло на карту: **{card} zł**\n💰 Твоя заработанная сумма: **{total} zł**\n➖➖➖➖➖➖➖\n🔸 **Неучтенный остаток (Nierozliczone saldo): {env} zł**",
        "audit_err": "⚠️ Нет записей о рабочих днях за {month}.",
        "hist_err": "📭 За {month} нет сохраненных смен.",
        "hist_ok": "📜 **История смен за {month}**\nНажми ❌ для удаления ошибочной записи:\n\n",
        "set_ok": "⚙️ <b>Настройки успешно сохранены!</b>",
        "err": "⚠️ Ошибка обработки данных.",
        "del_ok_alert": "✅ Смена за {date} удалена!",
        "del_ok_msg": "🗑 Запись за **{date}** была успешно удалена из базы.",
        "del_err": "⚠️ Запись не найдена или уже удалена.",
        "pro_alert": "⭐ PRO-подписка успешно активирована!",
        "pro_msg": "🎉 **Добро пожаловать в PRO-клуб!**\n\nТвой статус успешно обновлен. Теперь все твои Excel-отчеты формируются в профессиональном виде.\nСпасибо, что инвестируешь в свое время и поддерживаешь проект!",
        
        "excel_headers": ["Дата", "День", "Статус","Объект", "Авто", "Маршрут", "Всего ч.", "Руль", "50%", "100%", "Командировка", "Бонусы", "Брутто", "NETTO"],
        "excel_caption": "📊 Твоя зарплата за {month}\n🕒 Отработано: **{hours} ч.**\n💰 Всего заработано : **{net} zł**",
        "empty_db": "🤷‍♂️ В базе пока нет сохраненных отчетов.",
        
        "btn_panel": "📱 Открыть панель",
        "btn_help": "🚀 Как это работает?",
        "btn_feedback": "💬 Отзывы и идеи",
        "btn_coffee_10": "☕️ Угостить напарника кофе (10 zł)",
        "btn_lunch_30": "🍕 Обед для коллеги (30 zł)",
        "btn_pro": "⭐ Активировать PRO-подписку",
        "opt_work": "💼 Работа",
        "opt_l4": "💊 Больничный (L4)",
        "opt_urlop": "🌴 Отпуск",
        "help_text": (
            "🤖 **Как я работаю? Все просто!**\n\n"
            "📱 **ИНТЕРАКТИВНАЯ ПАНЕЛЬ**\n"
            "Нажми кнопку «Открыть панель» — это твой главный инструмент. Там три вкладки:\n"
            "1️⃣ **Смена** — для записи отработанных часов, больничных и отпусков.\n"
            "2️⃣ **Отчеты** — для выгрузки Excel, аудита зарплаты и удаления ошибочных смен.\n"
            "3️⃣ **Настройки** — для указания твоих ставок и финансовой цели.\n\n"
            "🌍 **УМНАЯ ЛОГИСТИКА И ВАЛЮТА**\n"
            "Если ты впишешь маршрут, но не укажешь часы вождения, я посчитаю их сам! А если отметишь галочку «Заграница», я переведу заработок из Евро в Злотые по актуальному курсу NBP."
        ),
        "feedback_msg": "💡 Есть идея, как улучшить приложение? Или нашел баг?\n\nНапиши напрямую разработчику:\n👉 [Написать программисту](https://t.me/+1tajf8L_zck5NTQy)",
        "overwork_msg": "{hours} ч. за смену — это мощно! Но не забывай про отдых и личные дела. Здоровье важнее переработок!",        
        "l4_loss_msg": "**ИИ-Аналитика:** Здоровье важнее денег! Но для справки: больничный ({count} дн.) стоил тебе потери около **{loss} zł** чистыми.",
        
        # --- NEW KEYS ---
        "menu_btn": "📱 Панель",
        "menu_msg": "⚡️ Интерактивная панель теперь всегда доступна по кнопке меню слева от поля ввода!",
        "voice_status_listening": "🎧 Слушаю и анализирую...",
        "voice_status_transcribing": "🧠 Расшифровываю аудио...",
        "voice_status_analyzing": "🤖 Анализирую смену с помощью ИИ...",
        "welcome_text": "👋 Привет! Я Кася — твой умный ИИ-помощник по учету работы и зарплаты в Польше! 👩‍💼\n\nС моей помощью ты сможешь легко:\n1️⃣ Вести точный учет рабочих смен, часов на объекте и времени за рулем ⏱\n2️⃣ Контролировать расчеты официальной зарплаты (нетто/брутто), больничных (L4) и отпусков 🌴\n3️⃣ Управлять командировочными (диетами) с автопереводом валют по курсу NBP 💶\n4️⃣ Накапливать средства в виртуальной «копилке» и отслеживать движение к своей финансовой цели 🎯\n\n⚠️ **Юридический дисклеймер:**\nБот предоставляет исключительно математические расчеты и аналитические инструменты (Audyt wyrównania, Nierozliczone saldo) для самоконтроля. Пользователь несет полную личную ответственность за декларирование своих доходов и уплату налогов в соответствии с законодательством Республики Польша.\n\nЧтобы начать свой путь к финансовому порядку, нажми кнопку **«📱 Панель»** ниже! 👇",
        "excel_boss_headers": ["Дата", "День", "Статус", "Объект", "Авто", "Маршрут", "Всего ч.", "Руль", "50%", "100%"],
        "excel_boss_caption": "📊 Операционный отчет за {month}\n🕒 Всего отработано: **{hours} ч.**",
        "excel_pure_logistics_headers": ["Дата", "День", "Маршрут", "Авто", "Часы за рулем"],
        "excel_pure_logistics_caption": "🚚 Отчет для логиста за {month}\n🚗 Всего за рулем: **{hours} ч.**",
        "choose_month": "📅 Выбери месяц для формирования отчета:",
        "btn_edit_log": "✏️ Изменить",
        "feedback_help": "💡 Пожалуйста, напиши свой отзыв или предложение после команды.\n\nПример: `/feedback Добавьте возможность выбирать цвет темы!`",
        "feedback_sent": "✅ Спасибо! Твой отзыв успешно отправлен разработчику.",
        "feedback_error": "❌ Произошла ошибка при отправке отзыва. Пожалуйста, попробуй позже.",
        "vision_analyzing": "👁 Изучаю фото...",
        "vision_not_recognized": "🤷‍♂️ Не смог распознать машину или номер. Попробуй другой ракурс!",
        "vision_recognized": "🚗 **Машина успешно распознана!**\n\n**Авто:** {car}\n**Номер:** {plate}\n\n✅ Сохранено в Гараж.",
        "vision_error": "⚠️ Ошибка при анализе фото: {err}",
        "voice_analyzing": "🎧 Слушаю и анализирую...",
        "voice_nbp_request": "🌍 Кася обращается в Нацбанк за курсом на {date_arg}...",
        "voice_finalizing": "🧠 Формирую финальный отчет...",
        "voice_received": "🎙 **Голосовой отчет принят!**\n\n📅 Дата: {date} ({day})\n📍 Локация: {loc}\n🕒 Работа: {hours} ч. | 🚗 За рулем: {drive} ч.\n💰 **На руки: {net:.2f} zł**\n{eur}\n✅ *Смена с учетом налогов и бонусов сохранена в базу!*",
        "voice_error": "⚠️ Ошибка расшифровки: {err}",
        "voice_eur_text": "🌍 Курс NBP: {rate} zł\n",
        "clarify_shift": "⚠️ **Уточните данные смены:**\n• {question}",
        "q_work_hours": "Сколько часов ты отработал?",
        "q_driving_hours": "Сколько часов провёл за рулём? (если не ехал — ответь «0»)",
        "q_location": "На каком объекте или в каком городе работал?",
        "voice_status_processing": "🤖 Обрабатываю...",
        "voice_status_analyzing_reply": "🤖 Анализирую ответ...",

        # --- VOICE SHIFT DRAFT & CONFIRMATION ---
        "draft_title": "📝 **Черновик смены:**",
        "draft_date": "📅 Дата",
        "draft_location": "📍 Локация",
        "draft_work": "🕒 Работа",
        "draft_drive": "🚗 Вождение",
        "draft_status_label": "📋 Статус",
        "draft_unknown": "Не указано",
        "draft_confirm": "**Сохранить эту смену в базу данных?**",
        "btn_yes": "Да ✅",
        "btn_no": "Нет ❌",
        "shift_closed": "🧾 <b>СМЕНА ЗАКРЫТА</b> 🧾",
        "shift_date": "📅 <b>Дата:</b>",
        "shift_status_label": "🛠 <b>Статус:</b>",
        "shift_object": "📍 <b>Объект:</b>",
        "shift_onsite": "⏱ На объекте:",
        "shift_driving": "🚗 За рулем:",
        "shift_daily_total": "💰 <b>ИТОГИ ДНЯ:</b>",
        "shift_net": "💵 На руки:",
        "shift_gross": "📄 Брутто:",
        "shift_card": "💳 На карту:",
        "shift_saved_fallback": "✅ **Смена успешно сохранена в базу данных!**",
        "shift_error_save": "⚠️ Ошибка при сохранении смены в базу данных.",
        "shift_cancelled": "❌ **Ввод смены отменен.**",
        "shift_total_count": "Всего смен: {total}",
        "coffee_invite": "Угостить Касю кофе",
    },
    "UKR": {
        "saving": "⏳ Зберігаю...",
        "report_wait": "⏳ Формую звіт за {month}...",
        "total_month": "Всього за місяць:",
        "freemium": "🤝 **Напарнику, хвилинку уваги!**\n\nЦе твій **{count}-й** згенерований звіт. Я економлю тобі купу часу на звірках з офісом та розрахунках податків.\n\nЩоб бот працював стабільно і розвивався далі, ти можеш підтримати проєкт символічною сумою «на каву ☕».",
        "audit_ok": "📊 **Аудит за {month}**\n\n💳 Прийшло на карту: **{card} zł**\n💰 Твій загальний заробіток: **{total} zł**\n〰️〰️〰️〰️〰️〰️〰️\n⚖️ **Nierozliczone saldo: {env} zł**",
        "audit_err": "⚠️ Немає записів про робочі дні за {month}.",
        "hist_err": "📭 За {month} немає збережених змін.",
        "hist_ok": "📜 **Історія змін за {month}**\nНатисни ❌ для видалення помилкового запису:\n\n",
        "set_ok": "⚙️ <b>Налаштування успішно збережено!</b>",
        "err": "⚠️ Помилка обробки даних.",
        "del_ok_alert": "✅ Зміну за {date} видалено!",
        "del_ok_msg": "🗑 Запис за **{date}** був успішно видалений з бази.",
        "del_err": "⚠️ Запис не знайдено або вже видалено.",
        "pro_alert": "⭐ PRO-підписку успішно активовано!",
        "pro_msg": "🎉 **Ласкаво просимо до PRO-клубу!**\n\nТвій статус успішно оновлено. Тепер усі твої Excel-звіти формуються у професійному вигляді.\nДякую, що інвестуєш у свій час і підтримуєш проєкт!",
        
        "excel_headers": ["Дата", "День", "Статус","Об'єкт", "Авто", "Маршрут", "Всього год.", "Кермо", "50%", "100%", "Відрядження", "Бонуси", "Брутто", "NETTO"],
        "excel_caption": "📊 Твоя зарплата за {month}\n🕒 Відпрацьовано: **{hours} год.**\n💰 Всього зароблено : **{net} zł**",
        "empty_db": "🤷‍♂️ В цьому місяці у тебе ще немає збережених звітів.",
        
        "btn_panel": "📱 Відкрити панель",
        "btn_help": "🚀 Як це працює?",
        "btn_feedback": "💬 Відгуки та ідеї",
        "btn_coffee_10": "☕️ Пригостити напарника кавою (10 zł)",
        "btn_lunch_30": "🍕 Обід для колеги (30 zł)",
        "btn_pro": "⭐ Активувати PRO-підписку",
        "opt_work": "💼 Робота",
        "opt_l4": "💊 Лікарняний (L4)",
        "opt_urlop": "🌴 Відпустка",
        "help_text": (
            "🤖 **Як я працюю? Це дуже просто!**\n\n"
            "📱 **ІНТЕРАКТИВНА ПАНЕЛЬ**\n"
            "Тисни кнопку «Відкрити панель» — це твій головний інструмент. Там три вкладки:\n"
            "1️⃣ **Зміна** — для запису відпрацьованих годин, лікарняних та відпусток.\n"
            "2️⃣ **Звіти** — для вивантаження Excel, аудиту зарплати та видалення помилкових змін.\n"
            "3️⃣ **Налаштування** — для вказівки твоїх ставок та фінансової цілі.\n\n"
            "🌍 **РОЗУМНА ЛОГІСТИКА ТА ВАЛЮТА**\n"
            "Якщо ти впишеш маршрут, але не вкажеш години за кермом, я порахую їх сам! А якщо відмітиш «Закордон», я переведу заробіток з Євро в Злоті за актуальним курсом NBP."
        ),
        "feedback_msg": "💡 Є ідея, як покращити додаток? Або знайшов помилку?\n\nНапиши безпосередньо розробнику:\n👉 [Написати програмісту](https://t.me/+1tajf8L_zck5NTQy)",
        "overwork_msg": "{hours} год за зміну — це потужно! Але не забувай про відпочинок та особисті справи. Здоров'я важливіше!",        
        "l4_loss_msg": "**Штучний Інтелект:** Здоров'я дорожче за гроші! Але для довідки: цей лікарняний ({count} дн.) коштував тобі втрати близько **{loss} zł** чистими.",
        
        # --- NEW KEYS ---
        "menu_btn": "📱 Панель",
        "menu_msg": "⚡️ Інтерактивна панель тепер завжди доступна за кнопкою меню зліва від поля введення!",
        "voice_status_listening": "🎧 Слухаю та аналізую...",
        "voice_status_transcribing": "🧠 Розшифровую аудіо...",
        "voice_status_analyzing": "🤖 Аналізую зміну за допомогою ШІ...",
        "welcome_text": "👋 Привіт! Я Кася — твій розумний ШІ-помічник з обліку роботи та зарплати в Польщі! 👩‍💼\n\nЗ моєю допомогою ти зможеш легко:\n1️⃣ Вести точний облік робочих змін, годин на об'єкті та часу за кермом ⏱\n2️⃣ Контролювати розрахунки офіційної зарплати (нетто/брутто), лікарняних (L4) та відпусток 🌴\n3️⃣ Керувати відрядженнями (дієтами) з автопереведенням валют за курсом NBP 💶\n4️⃣ Накопичувати кошти у віртуальній «скарбничці» та відстежувати рух до своєї фінансової цілі 🎯\n\n⚠️ **Юридичний дисклеймер:**\nБот надає виключно математичні розрахунки та аналітичні інструменти (Audyt wyrównania, Nierozliczone saldo) для самоконтроля. Користувач несе повну особисту ответственность за декларування своїх доходів та сплату податків відповідно до законодавства Республіки Польща.\n\nЩоб почати свій шлях до фінансового порядку, натисни кнопку **«📱 Панель»** нижче! 👇",
        "excel_boss_headers": ["Дата", "День", "Статус", "Об'єкт", "Авто", "Маршрут", "Всього год.", "Кермо", "50%", "100%"],
        "excel_boss_caption": "📊 Операційний звіт за {month}\n🕒 Всього відпрацьовано: **{hours} год.**",
        "excel_pure_logistics_headers": ["Дата", "День", "Маршрут", "Авто", "Години за кермом"],
        "excel_pure_logistics_caption": "🚚 Звіт для логіста за {month}\n🚗 Всього за кермом: **{hours} год.**",
        "choose_month": "📅 Обери місяць для формування звіту:",
        "btn_edit_log": "✏️ Змінити",
        "feedback_help": "💡 Будь ласка, напиши свій відгук або пропозицію після команди.\n\nПриклад: `/feedback Додайте можливість обирати колір теми!`",
        "feedback_sent": "✅ Дякую! Твій відгук успішно надіслано розробнику.",
        "feedback_error": "❌ Виникла помилка під час відправлення відгуку. Будь ласка, спробуй пізніше.",
        "vision_analyzing": "👁 Вивчаю фото...",
        "vision_not_recognized": "🤷‍♂️ Не вдалося розпізнати машину або номер. Спробуй інший ракурс!",
        "vision_recognized": "🚗 **Машину успішно розпізнано!**\n\n**Авто:** {car}\n**Номер:** {plate}\n\n✅ Збережено в Гараж.",
        "vision_error": "⚠️ Помилка при аналізі фото: {err}",
        "voice_analyzing": "🎧 Слухаю та аналізую...",
        "voice_nbp_request": "🌍 Кася звертається до Нацбанку за курсом на {date_arg}...",
        "voice_finalizing": "🧠 Формую фінальний звіт...",
        "voice_received": "🎙 **Голосовий звіт прийнято!**\n\n📅 Дата: {date} ({day})\n📍 Локація: {loc}\n🕒 Робота: {hours} год. | 🚗 За кермом: {drive} год.\n💰 **На руки: {net:.2f} zł**\n{eur}\n✅ *Зміна з урахуванням податків та бонусів збережена в базу!*",
        "voice_error": "⚠️ Помилка розшифровки: {err}",
        "voice_eur_text": "🌍 Курс NBP: {rate} zł\n",
        "clarify_shift": "⚠️ **Уточніть дані зміни:**\n• {question}",
        "q_work_hours": "Скільки годин ти відпрацював?",
        "q_driving_hours": "Скільки годин провів за кермом? (якщо не їхав — відповідай «0»)",
        "q_location": "На якому об'єкті або в якому місті працював?",
        "voice_status_processing": "🤖 Обробляю...",
        "voice_status_analyzing_reply": "🤖 Аналізую відповідь...",

        # --- VOICE SHIFT DRAFT & CONFIRMATION ---
        "draft_title": "📝 **Чернетка зміни:**",
        "draft_date": "📅 Дата",
        "draft_location": "📍 Локація",
        "draft_work": "🕒 Робота",
        "draft_drive": "🚗 Водіння",
        "draft_status_label": "📋 Статус",
        "draft_unknown": "Не вказано",
        "draft_confirm": "**Зберегти цю зміну в базу даних?**",
        "btn_yes": "Так ✅",
        "btn_no": "Ні ❌",
        "shift_closed": "🧾 <b>ЗМІНА ЗАКРИТА</b> 🧾",
        "shift_date": "📅 <b>Дата:</b>",
        "shift_status_label": "🛠 <b>Статус:</b>",
        "shift_object": "📍 <b>Об'єкт:</b>",
        "shift_onsite": "⏱ На об'єкті:",
        "shift_driving": "🚗 За кермом:",
        "shift_daily_total": "💰 <b>ПІДСУМКИ ДНЯ:</b>",
        "shift_net": "💵 На руки:",
        "shift_gross": "📄 Брутто:",
        "shift_card": "💳 На картку:",
        "shift_saved_fallback": "✅ **Зміну успішно збережено в базу даних!**",
        "shift_error_save": "⚠️ Помилка при збереженні зміни в базу даних.",
        "shift_cancelled": "❌ **Введення зміни скасовано.**",
        "shift_total_count": "Всього змін: {total}",
        "coffee_invite": "Пригостити Касю кавою",
    },
    "PL": {
        "saving": "⏳ Zapisuję...",
        "report_wait": "⏳ Generuję raport za {month}...",
        "total_month": "Razem za miesiąc:",
        "freemium": "🤝 **Kolego, chwila uwagi!**\n\nTo Twój **{count}.** wygenerowany raport. Oszczędzam Ci mnóstwo czasu na rozliczeniach z biurem i podatkach.\n\nAby bot działał stabilnie i się rozwijał, możesz wesprzeć projekt symboliczną kwotą «na kawę ☕».",
        "audit_ok": "📊 **Audyt za {month}**\n\n💳 Wpłynęło na konto: **{card} zł**\n💰 Całkowity zarobek: **{total} zł**\n〰️〰️〰️〰️〰️〰️〰️\n⚖️ **Nierozliczone saldo: {env} zł**",
        "audit_err": "⚠️ Brak zapisów o dniach pracy w {month}.",
        "hist_err": "📭 Brak zapisanych zmian w {month}.",
        "hist_ok": "📜 **Historia zmian w {month}**\nKliknij ❌, aby usunąć błędny wpis:\n\n",
        "set_ok": "⚙️ <b>Ustawienia zostały zapisane!</b>",
        "err": "⚠️ Błąd przetwarzania danych.",
        "del_ok_alert": "✅ Zmiana z {date} została usunięta!",
        "del_ok_msg": "🗑 Wpis z **{date}** został pomyślnie usunięty z bazy.",
        "del_err": "⚠️ Wpis nie został znaleziony lub już go usunięto.",
        "pro_alert": "⭐ Subskrypcja PRO została pomyślnie aktywowana!",
        "pro_msg": "🎉 **Witamy w klubie PRO!**\n\nTwój status został pomyślnie zaktualizowany. Teraz wszystkie Twoje raporty Excel są generowane w profesjonalnym formacie.\nDziękujemy za wsparcie projektu!",
        
        "excel_headers": ["Data", "Dzień", "Status","Obiekt", "Auto", "Trasa", "Suma h", "Jazda", "50%", "100%", "Delegacja", "Dodatki", "Brutto", "NETTO"],
        "excel_caption": "📊 Twoja wypłata za {month}\n🕒 Przepracowano: **{hours} h.**\n💰 Zarobiono łącznie : **{net} zł**",
        "empty_db": "🤷‍♂️ W tym miesiącu nie masz jeszcze zapisanych raportów.",
        
        "btn_panel": "📱 Otwórz panel",
        "btn_help": "🚀 Jak to działa?",
        "btn_feedback": "💬 Opinie i pomysły",
        "btn_coffee_10": "☕️ Postaw koledze kawę (10 zł)",
        "btn_lunch_30": "🍕 Obiad dla kolegi (30 zł)",
        "btn_pro": "⭐ Aktywuj subskrypcję PRO",
        "opt_work": "💼 Praca",
        "opt_l4": "💊 Zwolnienie (L4)",
        "opt_urlop": "🌴 Urlop",
        "help_text": (
            "🤖 **Jak działam? To proste!**\n\n"
            "📱 **INTERAKTYWNY PANEL**\n"
            "Kliknij przycisk «Otwórz panel» — to Twoje główne narzędzie. Są tam trzy zakładki:\n"
            "1️⃣ **Zmiana** — do wpisywania przepracowanych godzin, L4 i urlopów.\n"
            "2️⃣ **Raporty** — do pobierania Excela, audytu wypłaty i usuwania błędnych wpisów.\n"
            "3️⃣ **Ustawienia** — do podania swoich stawek i celu finansowego.\n\n"
            "🌍 **INTELIGENTNA LOGISTYKA I WALUTA**\n"
            "Jeśli wpiszesz trasę, ale nie podasz godzin jazdy, sam je policzę! A jeśli zaznaczysz «Zagranica», przeliczę zarobek z Euro na Złotówki według aktualnego kursu NBP."
        ),
        "feedback_msg": "💡 Masz pomysł jak ulepszyć aplikację? Albo znalazłeś błąd?\n\nNapisz bezpośrednio do twórcy:\n👉 [Napisz do programisty](https://t.me/+1tajf8L_zck5NTQy)",
        "overwork_msg": "{hours}h na jednej zmianie to sporo! Pamiętaj o odpoczynku i życiu prywatnym. Zdrowie jest najważniejsze!",        
        "l4_loss_msg": "**AI-Asystent:** Zdrowie jest ważniejsze niż pieniądze! Ale informacyjnie: to L4 ({count} dni) kosztowało Cię ok. **{loss} zł** na czysto.",
        
        # --- NEW KEYS ---
        "menu_btn": "📱 Panel",
        "menu_msg": "⚡️ Interaktywny panel jest teraz zawsze dostępny pod przyciskiem menu po lewej stronie pola wprowadzania!",
        "voice_status_listening": "🎧 Słucham i analizuję...",
        "voice_status_transcribing": "🧠 Transkrybuję audio...",
        "voice_status_analyzing": "🤖 Analizuję zmianę za pomocą AI...",
        "welcome_text": "👋 Cześć! Jestem Kasia — Twój inteligentny asystent AI do rejestracji czasu pracy i wynagrodzeń w Polsce! 👩‍💼\n\nZe mną możesz łatwo:\n1️⃣ Prowadzić dokładną ewidencję zmian, godzin na obiekcie i czasu za kierownicą ⏱\n2️⃣ Kontrolować rozliczenia oficjalnego wynagrodzenia (netto/brutto), zwolnień (L4) i urlopów 🌴\n3️⃣ Zarządzać delegacjami (dietami) z automatycznym przeliczaniem walut według kursu NBP 💶\n4️⃣ Oszczędzać pieniądze w wirtualnej «skarbonce» i śledzić realizację swojego celu finansowego 🎯\n\n⚠️ **Zastrzeżenie prawne:**\nBot wykonuje wyłącznie obliczenia matematyczne oraz udostępnia narzędzia analityczne (Audyt wyrównania, Nierozliczone saldo) do samokontroli. Użytkownik ponosi pełną osobistą odpowiedzialność za zgłaszanie swoich dochodów i opłacanie podatków zgodnie z przepisami Rzeczypospolitej Polskiej.\n\nAby zacząć drogę do porządku finansowego, kliknij przycisk **«📱 Panel»** poniżej! 👇",
        "excel_boss_headers": ["Data", "Dzień", "Status", "Obiekt", "Auto", "Trasa", "Suma h", "Jazda", "50%", "100%"],
        "excel_boss_caption": "📊 Raport operacyjny za {month}\n🕒 Przepracowano łącznie: **{hours} h.**",
        "excel_pure_logistics_headers": ["Data", "Dzień", "Trasa", "Auto", "Godziny jazdy"],
        "excel_pure_logistics_caption": "🚚 Raport dla logistyka za {month}\n🚗 Całkowity czas za kierownicą: **{hours} h.**",
        "choose_month": "📅 Wybierz miesiąc do wygenerowania raportu:",
        "btn_edit_log": "✏️ Edytuj",
        "feedback_help": "💡 Napisz swoją opinię lub sugestię po komendzie.\n\nPrzykład: `/feedback Dodaj możliwość wyboru koloru motywu!`",
        "feedback_sent": "✅ Dziękujemy! Twoja opinia została pomyślnie wysłana do programisty.",
        "feedback_error": "❌ Wystąpił błąd podczas wysyłania opinii. Spróbuj ponownie później.",
        "vision_analyzing": "👁 Analizuję zdjęcie...",
        "vision_not_recognized": "🤷‍♂️ Nie udało się rozpoznać samochodu ani numeru rejestracyjnego. Spróbuj pod innym kątem!",
        "vision_recognized": "🚗 **Samochód został pomyślnie rozpoznany!**\n\n**Auto:** {car}\n**Numer:** {plate}\n\n✅ Zapisano w Garażu.",
        "vision_error": "⚠️ Błąd podczas analizy zdjęcia: {err}",
        "voice_analyzing": "🎧 Słucham i analizuję...",
        "voice_nbp_request": "🌍 Kasia zwraca się do NBP o kurs na dzień {date_arg}...",
        "voice_finalizing": "🧠 Tworzę raport końcowy...",
        "voice_received": "🎙 **Raport głosowy przyjęty!**\n\n📅 Data: {date} ({day})\n📍 Lokalizacja: {loc}\n🕒 Praca: {hours} h | 🚗 Za kierownicą: {drive} h\n💰 **Na rękę: {net:.2f} zł**\n{eur}\n✅ *Zmiana z uwzględnieniem podatków i bonusów została zapisana w bazie!*",
        "voice_error": "⚠️ Błąd rozszyfrowania: {err}",
        "voice_eur_text": "🌍 Kurs NBP: {rate} zł\n",
        "clarify_shift": "⚠️ **Dopracuj dane zmiany:**\n• {question}",
        "q_work_hours": "Ile godzin przepracowałeś?",
        "q_driving_hours": "Ile godzin spędziłeś za kierownicą? (jeśli nie jechałeś — odpowiedz «0»)",
        "q_location": "Na jakim obiekcie lub w jakim mieście pracowałeś?",
        "voice_status_processing": "🤖 Przetwarzam...",
        "voice_status_analyzing_reply": "🤖 Analizuję odpowiedź...",

        # --- VOICE SHIFT DRAFT & CONFIRMATION ---
        "draft_title": "📝 **Szkic zmiany:**",
        "draft_date": "📅 Data",
        "draft_location": "📍 Lokalizacja",
        "draft_work": "🕒 Praca",
        "draft_drive": "🚗 Jazda",
        "draft_status_label": "📋 Status",
        "draft_unknown": "Nie podano",
        "draft_confirm": "**Zapisać tę zmianę w bazie danych?**",
        "btn_yes": "Tak ✅",
        "btn_no": "Nie ❌",
        "shift_closed": "🧾 <b>ZMIANA ZAMKNIĘTA</b> 🧾",
        "shift_date": "📅 <b>Data:</b>",
        "shift_status_label": "🛠 <b>Status:</b>",
        "shift_object": "📍 <b>Obiekt:</b>",
        "shift_onsite": "⏱ Na obiekcie:",
        "shift_driving": "🚗 Za kierownicą:",
        "shift_daily_total": "💰 <b>PODSUMOWANIE DNIA:</b>",
        "shift_net": "💵 Na rękę:",
        "shift_gross": "📄 Brutto:",
        "shift_card": "💳 Na konto:",
        "shift_saved_fallback": "✅ **Zmiana została pomyślnie zapisana w bazie danych!**",
        "shift_error_save": "⚠️ Błąd podczas zapisywania zmiany w bazie danych.",
        "shift_cancelled": "❌ **Wprowadzanie zmiany anulowane.**",
        "shift_total_count": "Łącznie zmian: {total}",
        "coffee_invite": "Postaw Kasi kawę",
    },
    "ENG": {
        "saving": "⏳ Saving...",
        "report_wait": "⏳ Generating report for {month}...",
        "total_month": "Total for the month:",
        "freemium": "🤝 **Partner, just a moment of your attention!**\n\nThis is your **{count}-th** generated report. I save you a lot of time on reconciliations with the office and tax calculations.\n\nTo keep the bot stable and developing, you can support the project with a symbolic donation \"for coffee ☕\".",
        "audit_ok": "📊 **Audit for {month}**\n\n💳 Received on card: **{card} zł**\n💰 Your total earnings: **{total} zł**\n〰️〰️〰️〰️〰️〰️〰️\n⚖️ **Unresolved balance (Nierozliczone saldo): {env} zł**",
        "audit_err": "⚠️ No work day records for {month}.",
        "hist_err": "📭 No shifts saved for {month}.",
        "hist_ok": "📜 **Shift history for {month}**\nClick ❌ to delete an incorrect entry:\n\n",
        "set_ok": "⚙️ <b>Settings saved successfully!</b>",
        "err": "⚠️ Data processing error.",
        "del_ok_alert": "✅ Shift for {date} deleted!",
        "del_ok_msg": "🗑 The entry for **{date}** was successfully deleted from the database.",
        "del_err": "⚠️ Entry not found or already deleted.",
        "pro_alert": "⭐ PRO subscription successfully activated!",
        "pro_msg": "🎉 **Welcome to the PRO Club!**\n\nYour status has been successfully updated. Now all your Excel reports are generated in a professional design.\nThank you for investing in your time and supporting the project!",
        "excel_headers": ["Date", "Day", "Status", "Object", "Car", "Route", "Total Hours", "Driving", "50%", "100%", "Travel Allowance", "Bonuses", "Gross", "Net"],
        "excel_caption": "📊 Your salary for {month}\n🕒 Hours worked: **{hours} hrs**\n💰 Total earned: **{net} zł**",
        "empty_db": "🤷‍♂️ No reports saved in the database yet.",
        "btn_panel": "📱 Open Panel",
        "btn_help": "🚀 How it works?",
        "btn_feedback": "💬 Feedback & Ideas",
        "btn_coffee_10": "☕️ Buy partner a coffee (10 zł)",
        "btn_lunch_30": "🍕 Buy colleague a lunch (30 zł)",
        "btn_pro": "⭐ Activate PRO Subscription",
        "opt_work": "💼 Work",
        "opt_l4": "💊 Sick Leave (L4)",
        "opt_urlop": "🌴 Vacation",
        "help_text": (
            "🤖 **How do I work? It's simple!**\n\n"
            "📱 **INTERACTIVE PANEL**\n"
            "Click the \"Open Panel\" button — this is your main tool. It has three tabs:\n"
            "1️⃣ **Shift** — to record hours worked, sick leaves, and vacations.\n"
            "2️⃣ **Reports** — to export Excel, audit salary, and delete incorrect shifts.\n"
            "3️⃣ **Settings** — to specify your rates and financial goal.\n\n"
            "🌍 **SMART LOGISTICS AND CURRENCY**\n"
            "If you enter a route but don't specify driving hours, I will calculate them myself! And if you check \"Abroad\", I will convert your earnings from Euro to Polish Zloty (PLN) at the current NBP (National Bank of Poland) exchange rate."
        ),
        "feedback_msg": "💡 Have an idea to improve the app? Or found a bug?\n\nWrite directly to the developer:\n👉 [Write to Developer](https://t.me/+1tajf8L_zck5NTQy)",
        "overwork_msg": "{hours} hrs in one shift is impressive! But don't forget about rest and personal life. Health is more important than overtime!",
        "l4_loss_msg": "**AI Analytics:** Health is more important than money! But for reference: this Sick Leave (L4) ({count} days) cost you a loss of about **{loss} zł** net.",
        "menu_btn": "📱 Panel",
        "menu_msg": "⚡️ Interactive panel is now always accessible via the menu button to the left of the input field!",
        "welcome_text": (
            "👋 Hello! I am Kasia — your smart AI assistant for work tracking and payroll in Poland! 👩‍💼\n\n"
            "With my help, you can easily:\n"
            "1️⃣ Keep accurate track of work shifts, hours on site, and driving time ⏱\n"
            "2️⃣ Verify calculations for your official salary (Net/Gross), Sick Leave (L4), and Vacation 🌴\n"
            "3️⃣ Manage Travel Allowance (diet) with automatic currency conversion at the NBP rate 💶\n"
            "4️⃣ Save money in a virtual \"piggy bank\" and track progress toward your financial goal 🎯\n\n"
            "⚠️ **Legal Disclaimer:**\n"
            "The bot provides only mathematical calculations and analytical tools (Compensation Audit / Audyt wyrównania, Unresolved balance / Nierozliczone saldo) for self-control. The user bears full personal responsibility for declaring income and paying taxes in accordance with the legislation of the Republic of Poland.\n\n"
            "To start your journey to financial order, press the **«📱 Panel»** button below! 👇"
        ),
        "voice_status_listening": "🎧 Listening and analyzing...",
        "voice_status_transcribing": "🧠 Transcribing audio...",
        "voice_status_analyzing": "🤖 Analyzing shift using AI...",
        "excel_boss_headers": ["Date", "Day", "Status", "Object", "Car", "Route", "Total Hours", "Driving", "50%", "100%"],
        "excel_boss_caption": "📊 Operational report for {month}\n🕒 Total hours worked: **{hours} hrs**",
        "excel_pure_logistics_headers": ["Date", "Day", "Route", "Car", "Driving Hours"],
        "excel_pure_logistics_caption": "🚚 Logistics report for {month}\n🚗 Total driving hours: **{hours} hrs**",
        "choose_month": "📅 Select a month to generate the report:",
        "btn_edit_log": "✏️ Edit",
        "feedback_help": "💡 Please write your feedback or suggestion after the command.\n\nExample: `/feedback Add the option to choose a theme color!`",
        "feedback_sent": "✅ Thank you! Your feedback has been successfully sent to the developer.",
        "feedback_error": "❌ An error occurred while sending feedback. Please try again later.",
        "vision_analyzing": "👁 Examining photo...",
        "vision_not_recognized": "🤷‍♂️ Could not recognize the car or plate number. Try a different angle!",
        "vision_recognized": "🚗 **Car successfully recognized!**\n\n**Car:** {car}\n**Plate:** {plate}\n\n✅ Saved to Garage.",
        "vision_error": "⚠️ Error analyzing photo: {err}",
        "voice_analyzing": "🎧 Listening and analyzing...",
        "voice_nbp_request": "🌍 Kasia is requesting the exchange rate from the NBP for {date_arg}...",
        "voice_finalizing": "🧠 Finalizing report...",
        "voice_received": "🎙 **Voice report received!**\n\n📅 Date: {date} ({day})\n📍 Location: {loc}\n🕒 Work: {hours} hrs | 🚗 Driving: {drive} hrs\n💰 **Net payout: {net:.2f} zł**\n{eur}\n✅ *Shift with taxes and bonuses has been saved to the database!*",
        "voice_error": "⚠️ Transcription error: {err}",
        "voice_eur_text": "🌍 NBP Exchange Rate: {rate} zł\n",
        "clarify_shift": "⚠️ **Please clarify the shift details:**\n• {question}",
        "q_work_hours": "How many hours did you work?",
        "q_driving_hours": "How many hours did you spend driving? (if none, answer «0»)",
        "q_location": "At which location or city did you work?",
        "voice_status_processing": "🤖 Processing...",
        "voice_status_analyzing_reply": "🤖 Analyzing your reply...",

        # --- VOICE SHIFT DRAFT & CONFIRMATION ---
        "draft_title": "📝 **Shift Draft:**",
        "draft_date": "📅 Date",
        "draft_location": "📍 Location",
        "draft_work": "🕒 Work",
        "draft_drive": "🚗 Driving",
        "draft_status_label": "📋 Status",
        "draft_unknown": "Not specified",
        "draft_confirm": "**Save this shift to the database?**",
        "btn_yes": "Yes ✅",
        "btn_no": "No ❌",
        "shift_closed": "🧾 <b>SHIFT CLOSED</b> 🧾",
        "shift_date": "📅 <b>Date:</b>",
        "shift_status_label": "🛠 <b>Status:</b>",
        "shift_object": "📍 <b>Location:</b>",
        "shift_onsite": "⏱ On site:",
        "shift_driving": "🚗 Driving:",
        "shift_daily_total": "💰 <b>DAY SUMMARY:</b>",
        "shift_net": "💵 Net payout:",
        "shift_gross": "📄 Gross:",
        "shift_card": "💳 To account:",
        "shift_saved_fallback": "✅ **Shift successfully saved to the database!**",
        "shift_error_save": "⚠️ Error saving shift to the database.",
        "shift_cancelled": "❌ **Shift entry cancelled.**",
        "shift_total_count": "Total shifts: {total}",
        "coffee_invite": "Buy Kasia a coffee",
    }
}

MOTIVATIONS = {
    "RUS": [
        "✨ Отличная работа! Время заслуженного отдыха.",
        "✨ Капля за каплей — получается море. Ты на шаг ближе к цели!",
        "✨ Сегодняшний труд — это завтрашняя свобода. Отдыхай!",
        "✨ Смена закрыта успешно. Гордись собой и своим результатом!",
        "✨ Еще один день, еще один уверенный шаг к мечте.",
        "✨ Идеальная дисциплина. Теперь можно расслабиться.",
        "✨ Твои усилия сегодня создают твое спокойное завтра.",
        "✨ Отличный результат! Пусть вечер будет уютным.",
        "✨ Цель всё ближе. Ты большой молодец!",
        "✨ Завершена еще одна глава твоего пути. Выдыхай.",
        "✨ Время выдохнуть, перезагрузиться и набраться сил.",
        "✨ Прекрасно потрудился! Наслаждайся свободным временем.",
        "✨ Твоя настойчивость — твой главный капитал.",
        "✨ Оставь работу на работе. Сейчас время только для себя.",
        "✨ Маленькие, но регулярные шаги ведут к великим достижениям.",
        "✨ Гордись проделанной работой и отдыхай душой.",
        "✨ Баланс важен: ты отлично поработал, теперь отлично отдохни.",
        "✨ Сегодня ты сделал максимум. Спасибо за труд!",
        "✨ За каждым усилием следует награда. Твоя — это спокойный вечер.",
        "✨ Смена сдана. Впереди только приятные моменты!"
    ],
    "PL": [
        "✨ Świetna robota! Czas na zasłużony odpoczynek.",
        "✨ Kropla do kropli, a zbierze się morze. Jesteś o krok bliżej celu!",
        "✨ Dzisiejsza praca to jutrzejsza wolność. Odpoczywaj!",
        "✨ Zmiana zakończona sukcesem. Bądź z siebie dumny!",
        "✨ Kolejny dzień, kolejny pewny krok w stronę marzeń.",
        "✨ Idealna dyscyplina. Teraz możesz się zrelaksować.",
        "✨ Twoje dzisiejsze wysiłki tworzą twoje spokojne jutro.",
        "✨ Świetny wynik! Niech ten wieczór będzie przytulny.",
        "✨ Cel jest coraz bliżej. Dobra robota!",
        "✨ Kolejny rozdział twojej drogi za tobą. Odetchnij.",
        "✨ Czas wziąć głęboki oddech, zresetować się i nabrać sił.",
        "✨ Świetnie się spisałeś! Ciesz się czasem wolnym.",
        "✨ Twoja wytrwałość to twój największy kapitał.",
        "✨ Zostaw pracę w pracy. Teraz czas tylko dla ciebie.",
        "✨ Małe, ale regularne kroki prowadzą do wielkich osiągnięć.",
        "✨ Bądź dumny z wykonanej pracy i odpocznij.",
        "✨ Równowaga jest ważna: świetnie popracowałeś, teraz świetnie odpocznij.",
        "✨ Dzisiaj dałeś z siebie wszystko. Dziękuję za twoją pracę!",
        "✨ Po każdym wysiłku przychodzi nagroda. Twoją jest spokojny wieczór.",
        "✨ Zmiana zdana. Przed tobą tylko miłe chwile!"
    ],
    "UKR": [
        "✨ Відмінна робота! Час для заслуженого відпочинку.",
        "✨ Крапля за краплею — виходить море. Ти на крок ближче до мети!",
        "✨ Сьогоднішня праця — це завтрашня свобода. Відпочивай!",
        "✨ Зміна закрита успішно. Пишайся собою та своїм результатом!",
        "✨ Ще один день, ще один впевнений крок до мрії.",
        "✨ Ідеальна дисципліна. Тепер можна розслабитися.",
        "✨ Твої зусилля сьогодні створюють твоє спокійне завтра.",
        "✨ Чудовий результат! Нехай вечір буде затишним.",
        "✨ Мета все ближче. Ти молодець!",
        "✨ Завершена ще одна глава твого шляху. Видихай.",
        "✨ Час видихнути, перезавантажитися та набратися сил.",
        "✨ Чудово попрацював! Насолоджуйся вільним часом.",
        "✨ Твоя наполегливість — твій головний капітал.",
        "✨ Залиш роботу на роботі. Зараз час тільки для себе.",
        "✨ Маленькі, але регулярні кроки ведуть до великих досягнень.",
        "✨ Пишайся виконаною роботою і відпочивай душею.",
        "✨ Баланс важливий: ти чудово попрацював, тепер чудово відпочинь.",
        "✨ Сьогодні ти зробив максимум. Дякую за працю!",
        "✨ За кожним зусиллям слідує нагорода. Твоя — це спокійний вечір.",
        "✨ Зміна здана. Попереду тільки приємні моменти!"
    ],
    "ENG": [
        "✨ Great job! Time for a well-deserved rest.",
        "✨ Drop by drop makes an ocean. You are one step closer to your goal!",
        "✨ Today's effort is tomorrow's freedom. Get some rest!",
        "✨ Shift closed successfully. Be proud of yourself and your result!",
        "✨ Another day, another confident step toward your dream.",
        "✨ Perfect discipline. Now you can relax.",
        "✨ Your efforts today build a peaceful tomorrow.",
        "✨ Great result! Have a cozy evening.",
        "✨ The goal is getting closer. Well done!",
        "✨ Another chapter of your journey is complete. Breathe out.",
        "✨ Time to take a breath, reset, and recharge.",
        "✨ Worked wonderfully! Enjoy your free time.",
        "✨ Your persistence is your main asset.",
        "✨ Leave work at work. Now it's time for yourself.",
        "✨ Small but regular steps lead to great achievements.",
        "✨ Be proud of your work and rest your mind.",
        "✨ Balance is key: you worked hard, now rest well.",
        "✨ Today you did your best. Thank you for your work!",
        "✨ Every effort is followed by a reward. Yours is a peaceful evening.",
        "✨ Shift turned in. Only pleasant moments ahead!"
    ]
}

def get_random_motivation(lang_code="RUS"):
    """Returns a random motivational quote based on the language code."""
    quotes = MOTIVATIONS.get(lang_code, MOTIVATIONS["RUS"])
    return random.choice(quotes)